// Generated by CoffeeScript 1.3.3

define(["vendor/amd/backbone", "./Templates"], function(Backbone, Templates) {
  return Backbone.View.extend({
    className: "remoteStorage",
    initialize: function() {},
    render: function() {
      this.$el.html(Templates.RemoteStorage());
      return this.$el;
    }
  });
});
